// Curated phrases and seed words for Indian parliamentary discourse.
//
// Each topic array holds both multi-word phrases and unigram seeds together.
// Multi-word phrases are merged into single tokens BEFORE statistical bigram
// detection so the LDA vocabulary picks them up as one unit. Unigrams anchor
// each topic in the LDA vocabulary via the seeded-beta prior.
//
// RAW_PHRASES filters to multi-word entries (p.includes(' ')) so unigrams
// never enter the phrase-merge trie.
//
// Seed design rules (omega = muStar / total_seed_weight_per_topic):
//   - Keep 15–20 seeds per topic so each word gets a meaningful omega boost.
//   - Cross-topic duplicates are assigned to the first topic in SEED_GROUPS
//     order; remove them from all later topics to avoid wasting seed slots.
//   - Prefer the most corpus-distinctive unigram over a generic synonym.

// ── Constitutional / Legal ──

import { compileTrie } from "$lib/topic-modelling/phrase-matcher.js";

const CONSTITUTIONAL = [
  "right to information", "right to education", "right to food",
  "right to privacy", "right to life", "right to work", "right to property",
  "right to vote", "right to equality", "right to freedom",
  "fundamental right", "fundamental duty", "fundamental freedom",
  "directive principle", "directive principles of state policy",
  "basic structure", "basic structure doctrine",
  "judicial review", "judicial activism", "judicial overreach",
  "separation of power", "rule of law", "due process",
  "public interest litigation", "writ petition",
  "habeas corpus", "quo warranto",
  "concurrent list", "state list", "union list",
  "article fourteen", "article nineteen", "article twenty one",
  "article three seventy", "article three five a",
  "parliamentary privilege", "contempt of court", "contempt of parliament",
  "preventive detention", "national emergency",
  "presidential reference", "constitutional bench",
  "ordinance making power",
  "governor's rule", "president's rule", "constitutional governor",
  "electoral roll", "adult franchise",
  "moral turpitude", "election petition", "separate electorate",
  "representation of peoples", "dinesh goswami committee", "vohra committee",
  "muddiman committee",
  // seeds (25 — most distinctive; cross-topic words claimed here first)
  "constitution", "amendment", "judiciary",
  "tribunal", "sovereign", "republic", "democracy", "statute",
  "ordinance", "equality", "liberty", "constitutional",
  "judicial", "legislative", "directive", "writ",
  "detention", "franchise", "ballot", "electorate", "lokpal",
];

const MISC = [
  "undocumented migration", "legal action", "civic amenities",
  "spatial distribution", "environmental policies", "local authorities",
  "primary education", "secondary education", "higher education",
  "fair price shop", "failure of crop", "government hostel",
];

// ── Policy, Programs, Schemes ──
const POLICY = [
  "five year plan", "twelfth five year plan", "eleventh five year plan",
  "mid day meal", "mid day meal scheme",
  "public distribution system", "fair price shop",
  "minimum support price", "procurement price",
  "direct benefit transfer", "cash transfer",
  "green revolution", "white revolution", "blue revolution",
  "swachh bharat", "swachh bharat abhiyan", "swachh bharat mission",
  "make in india", "digital india", "skill india", "startup india",
  "stand up india", "atmanirbhar bharat",
  "jan dhan yojana", "pradhan mantri jan dhan yojana",
  "ayushman bharat", "pradhan mantri jan arogya yojana",
  "mahatma gandhi national rural employment guarantee",
  "national rural employment guarantee",
  "national food security",
  "right to education act",
  "right to information act",
  "goods and services tax",
  "value added tax",
  "foreign direct investment",
  "foreign institutional investor",
  "one nation one election", "one nation one tax",
  "universal basic income",
  "minimum wage",
  "maternity benefit", "paid leave", "paternity benefit",
  "climate change", "global warming", "carbon emission",
  "renewable energy", "solar power", "wind power", "nuclear power",
  "thermal power", "hydroelectric power",
  "demonetization",
  "agricultural produce market committee",
  "farm law",
  // seeds (7 — deliberately narrow; cross-topic words live elsewhere)
  "scheme", "program", "mission", "implementation", "beneficiary",
  "allocation", "planning",
];

// ── Institutions ──
const INSTITUTIONS = [
  "supreme court", "high court", "district court",
  "election commission",
  "comptroller and auditor general",
  "union public service commission", "state public service commission",
  "staff selection commission",
  "planning commission", "niti aayog",
  "reserve bank of india", "state bank of india",
  "central bureau of investigation", "enforcement directorate",
  "national investigation agency",
  "national human rights commission",
  "national commission for women",
  "national commission for scheduled castes",
  "national commission for scheduled tribes",
  "national commission for backward classes",
  "national commission for minorities",
  "finance commission", "central finance commission",
  "pay commission", "seventh pay commission",
  "law commission",
  "attorney general", "solicitor general",
  "chief justice", "chief minister", "prime minister", "deputy prime minister",
  "chief election commissioner",
  "lok sabha speaker", "rajya sabha chairman", "deputy speaker",
  "vidhan sabha", "vidhan parishad",
  "gram panchayat", "panchayati raj", "gram sabha", "zilla parishad",
  "municipal corporation", "urban local body", "rural local body",
  "comptroller general of accounts",
  "ministry of external affairs", "ministry of home affairs",
  "ministry of finance", "ministry of defence",
  "department of telecommunications",
  "panchayat samiti", "village panchayat", "panchayati raj institution",
  "local self government", "local body", "ward sabha",
  "district planning committee", "district forest officer",
  "electronic voting machine", "electoral reform", "chief electoral officer",
  "estimates committee", "taxation enquiry committee",
  // seeds (15 — institutional vocabulary not claimed by other topics)
  "commission", "committee", "ministry", "department", "authority",
  "board", "council", "agency", "bureau", "regulatory",
  "oversight", "statutory", "accountability", "transparency", "panchayat",
];

// ── Geography & Demographics ──
const GEOGRAPHY = [
  "jammu and kashmir", "andhra pradesh", "arunachal pradesh",
  "himachal pradesh", "madhya pradesh", "uttar pradesh", "uttarakhand",
  "west bengal", "tamil nadu", "north east", "north eastern",
  "scheduled caste", "scheduled tribe", "other backward class",
  "scheduled area", "fifth schedule", "sixth schedule",
  "below poverty line", "above poverty line",
  "economically weaker section",
  "rural area", "urban area", "semi urban", "peri urban",
  "tribal area", "hill area", "border area",
  "union territory",
  "special category state",
  "mandal commission", "havanour commission", "registrar general of india",
  "caste census", "census enumeration", "caste based enumeration",
  "socio-economic and caste census", "national population register",
  "national population policy",
  "national register of citizens", "citizenship registration",
  "house to house enumeration", "assam accord",
  "national commission on urbanisation", "satellite township",
  "smart cities mission", "national urban transport policy",
  // seeds (18 — demographic/spatial terms; border claimed by DEFENCE)
  "district", "village", "population", "census", "coastal",
  "demographic", "density", "migration", "resettlement", "enumeration",
  "caste", "subcaste", "citizenship", "immigrant", "urbanisation",
  "slum", "township", "registrar",
];

// ── Economic / Fiscal ──
const ECONOMIC = [
  "gross domestic product", "per capita income", "national income",
  "foreign exchange reserve",
  "balance of payment", "current account deficit", "fiscal deficit",
  "revenue deficit", "primary deficit",
  "non performing asset", "essential commodities act", "transport cost",
  "inflation rate", "growth rate", "interest rate", "lending rate",
  "wholesale price index", "consumer price index",
  "agricultural sector", "manufacturing sector", "service sector",
  "public sector", "private sector", "public sector undertaking",
  "small scale industry", "cottage industry", "micro small and medium enterprise",
  "cooperative society", "self help group",
  "stock exchange", "capital market", "money market",
  // seeds (20 — fiscal/trade terms; credit/debt claimed here before BANKING_FINANCE)
  "economy", "fiscal", "budget", "revenue", "expenditure",
  "inflation", "deficit", "trade", "export", "import",
  "growth", "income", "finance", "tax", "investment",
  "gdp", "excise", "tariff", "customs", "redistribution",
];

// ── Healthcare / Public Health ──
const HEALTHCARE = [
  "national rural health mission", "national health mission",
  "national health policy", "aiims", "all india institute of medical sciences",
  "primary health centre", "community health centre", "sub centre",
  "district hospital", "teaching hospital", "government hospital",
  "accredited social health activist", "asha worker",
  "anganwadi worker", "auxiliary nurse midwife",
  "integrated child development service", "integrated child development scheme",
  "affordable healthcare", "reproductive healthcare",
  "janani suraksha yojana", "reproductive and child health",
  "maternal mortality rate", "infant mortality rate", "child mortality rate",
  "maternal death", "neonatal death",
  "malnutrition rate", "severe acute malnutrition",
  "pulse polio", "polio eradication", "immunization program",
  "universal immunization", "routine immunization",
  "essential medicine", "generic medicine",
  "transplantation of human organ", "organ transplant",
  "medical council of india", "dental council of india",
  "indian medical association", "indian nursing council",
  "food safety and standards authority",
  "drug controller general",
  "rural health care", "bachelor of rural health care",
  "non communicable disease", "communicable disease",
  "national disease control",
  "rashtriya swasthya bima yojana", "health insurance",
  "universal health coverage", "health for all",
  "ayush", "allopathy", "homeopathy", "ayurveda",
  "telemedicine", "mobile health", "e health",
  "blood bank", "eye bank",
  "cancer treatment", "dialysis centre",
  "mental health", "mental illness",
  "disability certificate", "persons with disability",
  "vaccine", "vaccination drive",
  "epidemic control", "disease surveillance",
  "national aids control", "hiv aids",
  "tuberculosis control", "tb patient",
  "malaria control", "vector borne",
  "national one health programme",
  "ayushman bharat health infrastructure mission",
  // seeds (20 — clinical/public-health terms)
  "hospital", "medicine", "doctor", "patient", "disease",
  "treatment", "medical", "clinic", "drug", "epidemic",
  "mortality", "maternal", "infant", "surgery", "diagnosis",
  "pharmaceutical", "immunization", "malnutrition", "cancer", "pandemic",
];

// ── Banking, Finance & Taxation ──
const BANKING_FINANCE = [
  "non banking financial company",
  "housing finance company", "national housing bank",
  "pre payment penalty", "foreclosure charge",
  "home loan", "housing loan",
  "floating interest rate", "fixed interest rate",
  "bank loan recovery", "coercive recovery method",
  "asset reconstruction company",
  "debt recovery tribunal",
  "wilful defaulter", "loan waiver", "farm loan waiver",
  "merger and acquisition", "investment bank",
  "advance tax", "direct tax", "indirect tax",
  "income tax", "corporate tax", "wealth tax", "service tax",
  "tax evasion", "tax avoidance", "tax compliance",
  "black money", "benami transaction",
  "money laundering", "hawala transaction",
  "double taxation avoidance",
  "transfer pricing",
  "wealth tax act", "income tax act", "gift tax act",
  "estate duty act", "voluntary disclosure",
  "taxation enquiry commission", "mahalanobis committee",
  "revenue collection", "tax revenue",
  "disinvestment", "privatisation", "nationalisation",
  "public sector bank", "private sector bank",
  "cooperative bank", "regional rural bank",
  "priority sector lending", "directed credit",
  "financial inclusion", "banking correspondent",
  "pradhan mantri mudra yojana",
  "credit guarantee", "loan guarantee",
  "microfinance institution", "self help group linkage",
  "insurance penetration", "life insurance",
  "general insurance", "crop insurance",
  "insurance regulatory and development authority",
  "securities and exchange board of india",
  "pension fund regulatory and development authority",
  "forward market commission",
  "commodity exchange", "futures trading",
  // seeds (16 — banking-specific; credit/tax/investment claimed by ECONOMIC)
  "loan", "interest", "deposit", "borrower", "lender",
  "defaulter", "recovery", "mortgage", "insurance", "premium",
  "asset", "collateral", "microfinance", "dividend", "portfolio",
  "restructuring",
];

// ── Energy & Infrastructure ──
const ENERGY_INFRA = [
  "rajiv gandhi grameen vidyutikaran yojana",
  "rural electrification", "village electrification",
  "below poverty line household electrification",
  "cost of supply of electricity", "electricity tariff",
  "power finance corporation", "state electricity board",
  "transmission loss", "distribution loss",
  "aggregate technical and commercial loss",
  "power purchase agreement", "independent power producer",
  "captive power plant", "distributed generation",
  "ultra mega power project",
  "national power grid", "interstate transmission",
  "coal block allocation", "coal mine", "exploration of coal",
  "natural gas", "liquefied natural gas", "piped natural gas",
  "petroleum product", "oil refinery",
  "kerosene quota", "kerosene subsidy",
  "lpg cylinder", "cooking gas",
  "national highway", "state highway", "rural road",
  "pradhan mantri gram sadak yojana",
  "road construction", "bridge construction",
  "port development", "inland waterway",
  "railway electrification", "dedicated freight corridor",
  "metro rail", "rapid transit",
  "public private partnership", "viability gap funding",
  "infrastructure development finance company",
  "national bank for agriculture and rural development",
  "export import bank of india",
  "small industries development bank of india",
  "drinking water supply", "rural drinking water",
  "sanitation facility", "open defecation free",
  "solid waste management", "sewage treatment",
  "housing for all", "pradhan mantri awas yojana",
  "affordable housing", "slum redevelopment",
  "basic services to the urban poor", "master plan",
  "integrated housing and slum development programme",
  // seeds (16 — energy/utility terms; road/bridge/port/nuclear/railway claimed by
  //         TRANSPORT or DEFENCE which come later but these phrases keep them here
  //         as merged tokens; unigram seeds only cover what's distinctive here)
  "electricity", "power", "energy", "grid", "transmission",
  "distribution", "electrification", "coal", "petroleum",
  "renewable", "solar", "wind", "thermal", "hydro",
  "pipeline", "refinery", "infrastructure",
];

// ── Agriculture & Rural Economy ──
const AGRICULTURE = [
  "agricultural loan", "crop loan", "kisan credit card",
  "pradhan mantri fasal bima yojana", "national crop insurance",
  "soil health card", "soil testing",
  "drip irrigation", "sprinkler irrigation", "micro irrigation",
  "pradhan mantri krishi sinchayee yojana",
  "flood relief", "drought relief", "natural calamity relief",
  "agricultural produce market committee",
  "electronic national agriculture market",
  "minimum support price", "procurement operation",
  "food processing", "cold chain", "agro processing",
  "fertiliser subsidy", "urea subsidy",
  "pesticide regulation", "seed certification",
  "animal husbandry", "dairy development", "poultry farming",
  "fisheries development", "marine fisheries",
  "cooperative dairy", "milk producer cooperative",
  "land reform", "land acquisition", "land record",
  "water shed development", "soil conservation",
  "organic farming", "natural farming",
  "agri export", "horticulture development",
  "forestry development", "social forestry",
  "farm income", "doubling farmer income",
  "crop diversification",
  "land reforms act", "land to the tiller",
  "ceiling on agricultural holdings", "operation barga",
  "bengal tenancy act", "surplus land", "vested land",
  "family holding", "redistribution of land",
  "estate acquisition act", "agricultural income-tax",
  // seeds (22 — agrarian terms; flood/drought kept here as they dominate agri debate)
  "farmer", "agriculture", "crop", "irrigation", "soil",
  "seed", "fertilizer", "pesticide", "harvest", "yield",
  "drought", "flood", "monsoon", "kisan", "paddy",
  "dairy", "livestock", "horticulture", "fishery", "zamindari",
  "tenancy", "cultivator", "land lord"
];

// ── Environment & Ecology ──
const ENVIRONMENT = [
  "pollution control board", "central pollution control board",
  "state pollution control board",
  "environmental impact assessment", "scarcity", "famine",
  "environment clearance", "forest clearance",
  "forest rights act", "community forest right",
  "scheduled forest", "reserved forest",
  "wildlife sanctuary", "national park", "tiger reserve",
  "forest land", "wildlife protection act",
  "wetland conservation", "mangrove protection",
  "river conservation", "river rejuvenation",
  "ganga action plan", "namami gange", "clean ganga",
  "coastal regulation zone", "coastal management",
  "hazardous waste", "electronic waste", "plastic waste",
  "air quality index", "water quality standard",
  "carbon credit", "emission trading",
  "environmental tribunal", "national green tribunal",
  "biodiversity conservation", "biological diversity",
  "climate adaptation", "disaster risk reduction",
  "flood management", "drought proofing",
  "desertification control",
  "ozone depletion", "hydrofluorocarbon", "forest policy",
  "black buck", "reserve forest",
  "environment impact assessment", "expert appraisal committee",
  "forest survey of india", "forest conservation act",
  "environment protection act", "national forest policy",
  "joint forest management", "national biodiversity authority",
  "ministry of environment and forests",
  "national river conservation programme", "human elephant conflict",
  "man animal conflict", "chief wildlife warden",
  "principal chief conservator of forest", "divisional forest officer",
  "great indian bustard", "sustainable sand mining guideline",
  "green hydrogen", "kyoto protocol", "crop raiding",
  // seeds (20 — ecology terms; water/renewable/solar/wind claimed by earlier topics)
  "environment", "pollution", "forest", "wildlife", "climate",
  "ecology", "biodiversity", "conservation", "emissions", "carbon",
  "sustainable", "hazardous", "deforestation", "wetland", "mangrove",
  "poaching", "sanctuary", "habitat", "endangered", "plastic",
];

// ── Education & Skill Development ──
const EDUCATION = [
  "central university", "deemed university",
  "university grant commission", "university grants commission",
  "all india council for technical education",
  "national council for educational research and training",
  "kendriya vidyalaya", "navodaya vidyalaya",
  "sarva shiksha abhiyan", "rashtriya madhyamik shiksha abhiyan",
  "vocational education", "technical education",
  "skill development mission", "national skill development corporation",
  "pradhan mantri kaushal vikas yojana",
  "industrial training institute",
  "polytechnic college", "engineering college",
  "medical college", "dental college",
  "teacher training", "teacher education",
  "gross enrolment ratio", "dropout rate",
  "literacy rate", "female literacy",
  "adult education", "continuing education",
  "distance education", "open university",
  "scholarship scheme", "fellowship scheme",
  "post matric scholarship", "merit cum means scholarship",
  "educational loan", "student loan",
  "coaching scheme", "remedial coaching",
  "foreign scholarship", "commonwealth scholarship",
  "international student", "academic exchange",
  "research and development", "innovation fund",
  "science and technology", "scientific research",
  "kothari commission", "private university bill",
  "pupil teacher ratio", "compulsory primary education",
  // seeds (15 — education terms; scholarship claimed here before SOCIAL_WELFARE)
  "school", "college", "university", "education", "literacy",
  "enrollment", "dropout", "curriculum", "examination", "scholarship",
  "training", "skill", "vocational", "technical", "research",
];

// ── Social Welfare & Protection ──
const SOCIAL_WELFARE = [
  "integrated child protection scheme",
  "juvenile justice", "juvenile justice board",
  "child labour", "child trafficking", "missing child",
  "destitute child", "orphan care",
  "special juvenile police unit",
  "child marriage prevention",
  "beti bachao beti padhao",
  "domestic violence", "protection of women from domestic violence",
  "sexual harassment at workplace",
  "vishaka guideline",
  "women empowerment", "gender equality",
  "gender budget", "gender responsive planning",
  "women reservation bill",
  "maternity leave", "crèche facility",
  "old age pension", "widow pension", "disability pension",
  "indira gandhi national old age pension scheme",
  "social security net", "social protection floor",
  "national social assistance programme",
  "antyodaya anna yojana",
  "national rural livelihood mission", "backward region grant fund",
  "job card", "wage rate", "employment assurance scheme",
  "housing for poor", "indira awas yojana",
  "sanitation for poor", "nirmal bharat abhiyan",
  "manual scavenging", "prohibition of manual scavenging",
  "bonded labour", "migrant worker", "interstate migrant",
  "unorganised worker", "unorganised sector",
  "construction worker welfare", "domestic worker",
  "welfare board", "labour welfare fund",
  "scheduled caste welfare", "scheduled tribe welfare",
  "post matric hostel", "pre matric scholarship",
  "minority welfare", "waqf board", "minority institution",
  "person with disability", "barrier free environment",
  "disability rehabilitation", "assistive device",
  // seeds (18 — welfare/protection terms; labour/worker/poverty/migration/trafficking
  //         claimed by LABOUR, ECONOMIC, GEOGRAPHY, HOME_AFFAIRS respectively)
  "welfare", "backward", "marginalized", "minority", "tribal",
  "dalit", "women", "child", "disability", "orphan",
  "elderly", "pension", "vulnerable", "destitute", "rehabilitation",
  "empowerment", "gender", "livelihood",
];

// ── Defence & National Security ──
const DEFENCE = [
  "armed force", "defence force", "military force",
  "border security force", "central reserve police force",
  "central industrial security force", "indo tibetan border police",
  "national security guard",
  "defence budget", "defence expenditure", "defence procurement",
  "defence production",
  "defence research and development organisation",
  "ordnance factory",
  "ex serviceman", "war widow",
  "one rank one pension", "military pension",
  "ceasefire agreement", "line of control",
  "left wing extremism", "naxal movement",
  "counter terrorism", "anti terrorism",
  "nuclear doctrine", "no first use",
  "strategic partnership", "strategic autonomy",
  "internal security", "national security",
  "counter radicalization strategy", "task force on terrorism",
  // seeds (20 — security/military terms; nuclear claimed here, not in ENERGY_INFRA
  //         unigrams; border claimed here before GEOGRAPHY)
  "defence", "military", "army", "navy", "security",
  "border", "soldier", "weapon", "terrorism", "insurgency",
  "paramilitary", "veteran", "nuclear", "missile", "combat",
  "strategic", "naxal", "radicalisation", "intelligence", "surveillance",
];

// ── Foreign Affairs & Diplomacy ──
const FOREIGN_AFFAIRS = [
  "bilateral relation", "diplomatic relation",
  "foreign policy",
  "south asian association for regional cooperation",
  "bay of bengal initiative",
  "shanghai cooperation organisation",
  "united nations security council",
  "world trade organisation",
  "international monetary fund",
  "non alignment movement",
  "act east policy", "neighbourhood first policy",
  "look east policy",
  "consular service", "visa policy",
  "overseas citizen of india", "non resident indian",
  "diaspora welfare",
  "extradition treaty", "mutual legal assistance",
  "territorial dispute", "boundary dispute",
  "economic corridor",
  "free trade agreement", "preferential trade agreement",
  // seeds (15 — foreign-relations terms; international claimed here)
  "diplomatic", "foreign", "bilateral", "multilateral", "international",
  "ambassador", "treaty", "sanction", "embargo", "refugee",
  "asylum", "visa", "territory", "diaspora", "nri",
];

// ── Home Affairs, Law & Order ──
const HOME_AFFAIRS = [
  "law and order", "public order",
  "indian police service",
  "police reform", "police accountability",
  "crime rate", "crime statistics",
  "organised crime", "criminal syndicate",
  "drug trafficking", "narcotics control bureau",
  "human trafficking", "trafficking victim",
  "custodial death", "encounter killing",
  "prison reform", "undertrial prisoner",
  "witness protection", "prison overcrowding",
  "forensic science laboratory",
  "cyber crime", "cyber security",
  "national crime record bureau",
  "sexual assault", "rape case",
  "atrocity against scheduled caste",
  "communal riot", "communal violence", "hate crime",
  "unlawful activities prevention act",
  "official secrets act", "press council of india",
  "national security act", "freedom of speech",
  "freedom of the press", "press censorship",
  "digital personal data protection act",
  "central board of film censors", "political prisoner",
  // seeds (16 — policing/crime terms; trafficking/detention/extremism claimed earlier)
  "police", "crime", "criminal", "investigation", "prosecution",
  "arrest", "custody", "conviction", "prison", "forensic",
  "riot", "violence", "narcotic", "cybercrime", "atrocity",
  "sedition",
];

// ── Labour & Employment ──
const LABOUR = [
  "labour law", "labour reform", "labour force", "labor force",
  "employee state insurance", "provident fund",
  "employees provident fund organisation",
  "contract labour", "casual labour",
  "industrial dispute", "collective bargaining",
  "trade union", "workers union",
  "retrenchment", "layoff",
  "industrial tribunal", "labour court",
  "occupational safety", "industrial accident",
  "workmen compensation",
  "child labour prohibition",
  "equal remuneration", "gender pay gap",
  "employment generation", "job creation",
  "rural employment", "urban employment",
  "self employment",
  "apprenticeship training",
  "national pension scheme",
  "gratuity payment", "bonus payment",
  "platform worker", "gig economy",
  "unorganised worker", "unorganised sector",
  "construction worker welfare", "domestic worker",
  // seeds (15 — labour-market terms; training/skill claimed by EDUCATION)
  "labour", "worker", "employee", "employment", "wages",
  "salary", "union", "strike", "retrenchment", "layoff",
  "factory", "provident", "gratuity", "bonus", "apprentice",
];

// ── Transport & Connectivity ──
const TRANSPORT = [
  "indian railway", "railway ministry",
  "railway budget", "railway safety",
  "passenger train", "freight train",
  "dedicated freight corridor",
  "bullet train", "high speed rail",
  "civil aviation", "airport development",
  "directorate general of civil aviation",
  "air traffic control",
  "national highways authority of india",
  "waterway transport", "national waterway",
  "inland water transport",
  "shipping corporation", "major port",
  "logistics sector", "supply chain",
  "last mile connectivity",
  "vehicle emission standard",
  "road accident", "road safety",
  "traffic management",
  "metro project", "light rail transit",
  "intelligent transport system", "integrated transport hub",
  "cycling track",
  "gauge conversion", "amrit bharat station scheme",
  "railway over bridge", "world class railway station",
  "chenab bridge", "railway protection force",
  "irctc", "nhai", "morth", "bmrcl", "cmrl",
  // seeds (15 — transport terms; road/bridge/port/railway claimed here;
  //         nuclear/pipeline left to ENERGY_INFRA/DEFENCE)
  "railway", "train", "aviation", "airport", "highway",
  "road", "bridge", "tunnel", "port", "shipping",
  "freight", "passenger", "metro", "transport", "traffic",
];

// ── Telecommunications & Digital India ──
const TELECOM = [
  "telecom regulatory authority of india",
  "spectrum allocation", "spectrum auction",
  "mobile network", "broadband connectivity",
  "optical fibre network",
  "digital literacy",
  "national digital health mission",
  "national broadband mission",
  "internet connectivity", "internet access",
  "digital payment", "unified payment interface",
  "e governance", "e service",
  "national informatics centre",
  "data protection", "personal data",
  "artificial intelligence", "machine learning",
  "it enabled service",
  "data localisation",
  "social media regulation",
  "cybersecurity policy",
  "net neutrality",
  "call drop", "telecom tower",
  "information commission", "chief information commissioner",
  "all india radio", "good governance", "right to service act",
  "cable television networks regulation act",
  "common service centre", "cbfc",
  "central board of film certification",
  // seeds (15 — digital/telecom terms; cyber also appears in HOME_AFFAIRS as
  //         "cybercrime" — that's a different token; spectrum/data/network live here)
  "telecom", "digital", "internet", "mobile", "broadband",
  "spectrum", "data", "network", "technology", "software",
  "algorithm", "platform", "satellite", "broadcasting", "innovation",
];

// ── Procedural (sparingly — most parliamentary scaffolding is in stopwords) ──
const PROCEDURAL = [
  "question hour", "zero hour",
  "calling attention", "short notice question",
  "private member bill", "government bill",
  "standing committee", "select committee", "joint parliamentary committee",
  "estimates committee", "public accounts committee",
  "motion of thanks", "presidential address",
  "vote on account", "appropriation bill", "finance bill",
  "money bill", "constitution amendment bill",
  "vote of no confidence", "vote of confidence",
  // seeds (8 — procedural mechanics only; amendment/session live in CONSTITUTIONAL)
  "motion", "resolution", "debate", "adjournment",
  "quorum", "division", "vote", "tabled",
];

// Only multi-word entries go into the phrase-merge trie; unigrams are filtered out.
export const RAW_PHRASES = [
  ...CONSTITUTIONAL,
  ...POLICY,
  ...INSTITUTIONS,
  ...GEOGRAPHY,
  ...ECONOMIC,
  ...HEALTHCARE,
  ...BANKING_FINANCE,
  ...ENERGY_INFRA,
  ...AGRICULTURE,
  ...ENVIRONMENT,
  ...EDUCATION,
  ...SOCIAL_WELFARE,
  ...DEFENCE,
  ...FOREIGN_AFFAIRS,
  ...HOME_AFFAIRS,
  ...LABOUR,
  ...TRANSPORT,
  ...TELECOM,
  ...PROCEDURAL,
  ...MISC,
].filter(p => p.includes(" "));

// Ordered seed groups for Seeded LDA. Each inner array is one conceptual
// topic; the first min(K, SEED_GROUPS.length) topics get a dedicated prior
// boost. Order matters: a unigram is assigned to the FIRST group that claims
// it, so place the most domain-distinctive categories first.
export const SEED_GROUPS = [
  CONSTITUTIONAL,
  HEALTHCARE,
  ECONOMIC,
  POLICY,
  AGRICULTURE,
  ENERGY_INFRA,
  EDUCATION,
  SOCIAL_WELFARE,
  BANKING_FINANCE,
  ENVIRONMENT,
  DEFENCE,
  FOREIGN_AFFAIRS,
  HOME_AFFAIRS,
  LABOUR,
  TRANSPORT,
  TELECOM,
  GEOGRAPHY,
  INSTITUTIONS,
  PROCEDURAL,
  MISC,
];

export const TOPIC_PHRASES = compileTrie(RAW_PHRASES);

// Set of canonical merged forms ("right_to_information", "fundamental_right", …)
// — lets consumers cheaply distinguish a lexicon phrase from a statistical
// bigram in any token stream. Both look like "a_b" tokens.
export const PHRASE_MERGED_SET = new Set(
  RAW_PHRASES
    .map(p => p.toLowerCase().trim().split(/\s+/).filter(Boolean))
    .filter(toks => toks.length >= 2)
    .map(toks => toks.join("_"))
);
