export let text1 = [
  "Who should the nation pray to?",
  "Where do our leaders come from?",
  "Who must the economy feed?",
  "What can we dream?",
  "What should we read?",
  "What may the government know?",
  "What may the government say?",
  "Who are our future leaders?",
  "Who must we read?",
  "Who should our children pray to?",
  "What must our children read?",
  "What must our children do?",
  "Who may educate our children?",
  "What will our children learn?",
  "Who wrote our history?",
  "What language should our children speak?",
  "Where do we come from?",
  "What language can our children speak?",
  "What must our leaders speak?",
  "Where must our leaders come from?",
  "What will history talk about?",
  "Who do our children learn about?",
  "Who is precious to our history?",
  "Why is history precious?",
  "Why is history important?",
  "What will our children learn?",
  "What have children learnt before?",
  "Which children have learnt?",
  "Who decides which children learn?",
  "Who decides who learns what?",
  "Who is our family?",
  "Who should I marry?",
  "Who should I have children with?",
  "What may take care of us?",
  "What may gift peace to us?",
  "What must be heard?",
  "What must we answer?",
  "What is precious to us?",
  "What is precious to the state?",
  "Who do our leaders pray to?",
  "What do our leaders pray for?",
  "What is precious to the nation?",
  "What is precious to our leaders?",
];

export let text2 = [
  "Why do familes need visas?",
  "Whose kisses need visas",
  "Whose kisses need lisences",
  "Which marriages need papers",
  "Which lives need papers",
  "Whose lives are not questioned",
  "Who have addresses",
  "Who is benovelent?",
  "Are our skies benovelent?",
  "Why do we need the benovelent?",
  "Who must we trust?",
  "How long may we trust?",
  "When may we rise?",
  "How may we come together ?",
  "Who may drink our water?",
  "Where may our rivers flow?",
  "Who draws our rivers?",
  "Who draws from our rivers?",
  "What is priceless?",
  "Who blesses our lands?",
  "Who blesses our summers ?",
  "Who may drink our water?",
  "Where may our rivers flow?",
  "Who draws our rivers?",
  "Who draws from our rivers?",
  "What is priceless?",
  "Who blesses our lands?",
  "Who blesses our summers ?",
  "How may order be brought upon?",
  "How may we integrate us?",
  "Who may gift peace to us?",
  "How may we integrate them?",
  "Who may govern us?",
  "Who may govern them?",
  "How may we govern ?",
  "How may order be brought upon?",
  "How may we integrate us?",
  "Who may gift peace to us?",
  "How may we integrate them?",
  "Who may govern us?",
  "Who may govern them?",
  "How may we govern?",
];
